### ISSUE TITLE
Make the classname applied configurable

### ISSUE THREAD

**Issue by the-destro** [angular-ui/ui-scrollpoint#2]
It would be nice if you could override easily what class gets applied.

**Comment by kunKun-tx** [comment]
it will be even nicer if it can return some values. Right now i have to change the source code for that.

**Comment by PowerKiKi** [comment]
@eiclkun this seems to be very different than original issue isn't it ?

**Comment by kunKun-tx** [comment]
you are right, shall i create another feature request for that?

**Comment by PowerKiKi** [comment]
Rather than a feature request, it would be even better to create a PR. This project doesn't have any active core members. So while I do what I can to maintain it, if you want new features you'll have to step in.

**Comment by plong0** [comment]
Happy Saturday!  Here is a PR for the custom ui-scrollpoint-class feature, as well as the feature of a ui-scrollpoint-action callback function.

**Comment by PowerKiKi** [comment]
Released as 1.2.1
